name: PHP Matrix Testing for WordPress Plugins

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.0, 8.1]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, zip

      - name: Install Composer Dependencies
        run: composer install

      - name: Run PHPUnit Tests
        run: composer test